### PR TITLE
Per-file Cursor and Undo History

### LINKED ISSUE #146: Per-file Cursor and Undo History
As a visualization author, I want each file to have independent cursor placement and undo history, so that I don't experience unexpected glitches while working.

https://codemirror.net/doc/manual.html#api_doc

### PR DESCRIPTION
**Pull request by stushurik**
closes datavis-tech/vizhub-issue-tracker/issues/146

### CODE REVIEW

**Comment by stushurik** [comment]
@curran At first, I accidentally pushed changes directly to master, I had to revert it, so don't feel frustrated if you will see some un-approved commits in master

File: packages/neoFrontend/src/pages/VizPage/Body/Editor/CodeEditor/CodeArea/CodeAreaCodeMirror5/index.js [hunk 1]
```diff
@@ -27,6 +27,9 @@ const colorHash = new ColorHash();
 
 const fileIndexOfPath = (path) => path[1];
 
+const historyByFile = {}
```
Comment (curran) [inline packages/neoFrontend/src/pages/VizPage/Body/Editor/CodeEditor/CodeArea/CodeAreaCodeMirror5/index.js:30]: Nice. This is the sort of solution I was hoping to see. Great work!

**Review by curran — APPROVED** [review]
