### PR TITLE
Bug/356 viz title reset

### LINKED ISSUE #356: After deletion of fork title remains the same but should be profile page title
image

### PR DESCRIPTION
**Pull request by stushurik**
Closes datavis-tech/vizhub-issue-tracker/issues/356

### CODE REVIEW

File: packages/neoFrontend/src/pages/VizPage/Body/Viewer/index.js [hunk 1]
```diff
@@ -84,7 +84,13 @@ export const Viewer = () => {
 
   // Set title in browser tab.
   useEffect(() => {
+    const title = document.title;
+
     document.title = vizInfo.title;
+
+    return () => {
```
Comment (curran) [inline packages/neoFrontend/src/pages/VizPage/Body/Viewer/index.js:91]: Clever solution!

**Review by curran — APPROVED** [review]
LGTM
