### PR TITLE
Bug/493

### LINKED ISSUE #493: ESLint Not Quite Right
I put the new ESLint feature on staging and discovered it's not quite working correctly with JSX. Would you be able to investigate? Example: https://staging.vizhub.com/curran/9b881e62cb2442ea928eb89b42dda013?edit=files&file=index.js#L7 (Marks is used, but marked as unused)

image

### PR DESCRIPTION
**Pull request by stushurik**
Add basic react rules

Closes datavis-tech/vizhub-issue-tracker/issues/493

### CODE REVIEW

File: packages/neoFrontend/src/pages/VizPage/EditorModulesContext/codemirrorAddons/lint/jsxLint.js [hunk 1]
```diff
@@ -15,19 +15,21 @@ const parseErrors = (errors) => {
...
-  Promise.all([linterModulePromise, lintrcModulePromise]).then(
-    ([linterModule, lintrcModule]) => {
-      const Linter = linterModule.default;
-      const linter = new Linter();
-      const { config } = lintrcModule;
-      const results = linter.verify(text, config);
-      callback(parseErrors(results));
-    }
-  );
+  const jsxUsesReactRule = (await import('eslint-plugin-react/lib/rules/jsx-uses-react')).default;
```
Comment (curran) [inline packages/neoFrontend/src/pages/VizPage/EditorModulesContext/codemirrorAddons/lint/jsxLint.js:22]: Nice! I wonder if we could group the 3 async imports into one to improve performance. I believe as it stands, Webpack will perform 3 separate network requests. If we create a single module that has static imports for all 3 of these, and then add just one `await import` for that module, I think we can reduce network requests to only one. Potential for a follow-up PR.

**Review by curran — APPROVED** [review]
Looks good! Minor suggestion for performance improvement, can do as a follow-up PR.
